scribe-org/Scribe-Android

- .github/ISSUE_TEMPLATE/data_wikidata.yml
- .github/ISSUE_TEMPLATE/new_keyboard.yml
- .github/ISSUE_TEMPLATE/question.yml
> Adding Issue Templates of data, keyboard, question

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> Adding Issue Templates of bug and Feature with config file

- app/src/main/kotlin/org/scribe/activities/MainActivity.kt
- app/src/main/kotlin/org/scribe/activities/SettingsActivity.kt
- app/src/main/kotlin/org/scribe/helpers/Config.kt
- app/src/main/kotlin/org/scribe/helpers/Constants.kt
- app/src/main/res/layout-land/keyboard_key_preview.xml
- app/src/main/res/layout-land/keyboard_view_keyboard.xml
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/values/bools.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Only did a very minor change to set the default theme of the app to system's default theme.
> added default theme setting

- app/src/main/kotlin/org/scribe/activities/MainActivity.kt
- app/src/main/kotlin/org/scribe/activities/SettingsActivity.kt
- app/src/main/kotlin/org/scribe/views/MyKeyboardView.kt
- app/src/main/res/layout-land/keyboard_view_keyboard.xml
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/layout/keyboard_popup_keyboard.xml
- app/src/main/res/layout/keyboard_view_command_options.xml
- app/src/main/res/layout/keyboard_view_keyboard.xml
- app/src/main/res/values-night-v31/colors.xml
- app/src/main/res/values-v31/colors.xml
- app/src/main/res/values/colors.xml
[x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
---
The Pull request aims to add dark mode and light mode functionality to the application.The current approach adds a dark mode or light mode on the user clicking the checkbox which is present in the app settings. 
The changes have been tested the keyboard changes it color to a darker color when the user check the dark mode option in the settings . the application also changes to the dark mode theme given in the scheme present for the dark and light mode respectively 
-   #27
> feat:Added Dark Mode for the app as well as the keyboard

- app/src/main/java/be/scri/models/Clip.kt
---
- The issue fixes the app not building due to tableName in Clips.kt changed to lowercase.
> fix:Fixed crash due to tableName being changed to lowercase

- README.md
---
This pull request fixes the vertically stretched image in the `README.md` file for better display on mobile devices. I tested the change on both mobile and desktop views to ensure proper rendering.
-   #154
> Fix #154: Resolve stretched image in README.md for better view across all devices.

- app/src/main/java/be/scri/activities/MainActivity.kt
- app/src/main/java/be/scri/fragments/MainFragment.kt
- app/src/main/java/be/scri/fragments/SettingsFragment.kt
- app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
- app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
- app/src/main/java/be/scri/services/GermanKeyboardIME.kt
- app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
- app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
- app/src/main/java/be/scri/services/RussianKeyboardIME.kt
- app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
- app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
- app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
---
The pull request fixes the dark and light mode issues for the keyboard and the app on the first launch. 
-   #155
> fix:Fixed Dark mode issues and coloring issues

- app/src/main/res/layout/fragment_privacy_policy.xml
- app/src/main/res/layout/fragment_third_party.xml
> Henrikth93 android margin #144

- app/src/main/java/be/scri/extensions/ContextStyling.kt
- app/src/main/java/be/scri/helpers/CommonsConstants.kt
- app/src/main/java/be/scri/helpers/String.kt
- detekt.yml
> Fix ForEachOnRange detekt issues

- app/src/main/java/be/scri/fragments/SettingsFragment.kt
- app/src/main/java/be/scri/helpers/CustomAdapter.kt
- app/src/main/java/be/scri/models/TextItem.kt
- app/src/main/res/layout/card_view_text.xml
---
This PR is to add description below App language option.
Would appreciate feedback on this, thank you. :)
-   #142
> add app language description #142

- app/src/main/java/be/scri/extensions/Int.kt
- detekt.yml
> Fix ImplicitDefaultLocale

- app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt
- app/src/main/res/layout/fragment_language_settings.xml
This commit will add the menu items "Comma and period on ABC" and "Disable accent characters".
---
-   #147
> Added layout-related settings for the keyboard menu UI

- .github/workflows/pr_maintainer_checklist.yaml
-   [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
---
As discuses in [#Scribe-data@308 ](https://github.com/scribe-org/Scribe-Data/issues/300). Updated [pr_maintainer_checklist.yaml](https://github.com/axif0/Scribe-iOS/blob/2453891c2dadfdb97effb1bbd79aa43b90707a8d/.github/workflows/pr_maintainer_checklist.yaml) accordingly.
> Updating pr_maintainer_checklist workflow 

- detekt.yml
---
Set the empty catch box in the `detekt.yml` to true.
```
empty-blocks:
EmptyCatchBlock:
active: true
EmptyFunctionBlock
```
This change is not giving out any errors as of now indicating zero empty catch boxes in the repository.  I will be happy to work  in this regard if anything comes along the way 😄 
-   #184
> Update detekt.yml set Empty catch to true

- app/src/main/java/be/scri/helpers/DatabaseHelper.kt
- app/src/main/java/be/scri/helpers/RatingHelper.kt
- detekt.yml
---
While addressing other linting issues, I found that in the current main branch, these two detekt parameters can be enabled directly without returning errors. Therefore, these parameters can be modified here to check for corresponding errors in the future. 😊
-   #110
> Fix Long Parameter List

- app/src/main/java/be/scri/views/MyKeyboardView.kt
---
This PR fix dark mode callout with popup on keypress on.
-   #21
> Fix Dark Mode Base Callout

- app/src/main/java/be/scri/helpers/AlphanumericComparator.kt
- app/src/main/java/be/scri/helpers/DatabaseHelper.kt
- app/src/main/java/be/scri/helpers/MyKeyboard.kt
- app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
- app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
- app/src/main/java/be/scri/services/GermanKeyboardIME.kt
- app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
- app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
- app/src/main/java/be/scri/services/RussianKeyboardIME.kt
- app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
- app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
- app/src/main/java/be/scri/views/MyKeyboardView.kt
- detekt.yml
---
This pull requests fixes the linting issues caused due to nested block depth and complex methods as detected by detekt. 
-   #112 
-  #108
> Fix Linting issues due to Nested Block Depth and Complex Methods

- app/src/main/java/be/scri/helpers/PreferencesHelper.kt
- app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
- app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
- app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
- app/src/main/java/be/scri/services/GermanKeyboardIME.kt
- app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
- app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
- app/src/main/java/be/scri/services/RussianKeyboardIME.kt
- app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
- app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
- app/src/main/res/values/strings.xml
---
The PR adds docs for all the functions in the services directory. It also does some refractor of the general keyboard ime by moving all the shared preferences functions to the Preferences Helper in the helpers directory. 
-   #309
> Documentation for the files in the services directory 

- app/build.gradle.kts
- app/src/main/java/be/scri/ui/common/components/ItemCardContainerWithTitle.kt
- app/src/main/java/be/scri/ui/screens/InstallationScreen.kt
> increase font size

- app/src/main/java/be/scri/ui/common/bottombar/ScribeBottomBar.kt
- app/src/main/res/values/colors.xml
-   [] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)
---
-   closes #314
> change unselected color and remove tab bar animation

- app/src/main/java/be/scri/helpers/KeyboardBase.kt
- app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
- app/src/main/java/be/scri/ui/screens/settings/SettingsUtil.kt
- app/src/main/java/be/scri/views/KeyboardView.kt
- app/src/main/res/drawable/ic_left_arrow.xml
- app/src/main/res/drawable/ic_right_arrow.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/xml/conjugate_view_1x1.xml
- app/src/main/res/xml/conjugate_view_1x3.xml
- app/src/main/res/xml/conjugate_view_2x1.xml
- app/src/main/res/xml/conjugate_view_2x2.xml
- app/src/main/res/xml/conjugate_view_3x2.xml
---
This PR bring the conjugate views. I have implemented the conjugate views and tested them individual whether they look good on the keyboard in accordance with heigh and width.For now the conjugate button shows up the 3x2 conjugation view and the display left and right key don't do anything. I have not disabled the key actions for now.
-   #267
> Implement Conjugate Views

- app/src/main/java/be/scri/activities/MainActivity.kt
- app/src/main/java/be/scri/ui/common/appcomponents/ActionBar.kt
- app/src/main/java/be/scri/ui/common/appcomponents/HintDialog.kt
- app/src/main/java/be/scri/ui/common/appcomponents/PageTitle.kt
- app/src/main/java/be/scri/ui/common/bottombar/BottomBarScreen.kt
- app/src/main/java/be/scri/ui/models/ScribeItem.kt
- app/src/main/java/be/scri/ui/screens/InstallationScreen.kt
- app/src/main/java/be/scri/ui/screens/LanguageSettingsScreen.kt
- app/src/main/java/be/scri/ui/screens/PrivacyPolicyScreen.kt
- app/src/main/java/be/scri/ui/screens/ThirdPartyScreen.kt
- app/src/main/java/be/scri/ui/screens/WikimediaScreen.kt
- app/src/main/java/be/scri/ui/screens/about/AboutUtil.kt
- app/src/main/java/be/scri/ui/screens/settings/SettingsScreen.kt
- app/src/main/java/be/scri/ui/screens/settings/SettingsUtil.kt
- app/src/main/java/be/scri/ui/screens/settings/SettingsViewModel.kt
- detekt.yml
---
This pull request is documenting functions and classes present in be.scri.ui and be.scri.activities
-   #370
> Doc main activity

- app/src/androidTest/kotlin/be/scri/helpers/KeyboardTest.kt
---
This PR adds the tests for the backspace functionality
-   #429
> add: tests for backspace deletion

- app/src/androidTest/kotlin/be/scri/ui/screens/settings/SettingsScreenInstrumentedTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/be/scri/helpers/data/TranslationDataManager.kt
- app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
- app/src/main/java/be/scri/ui/screens/DataDownloadScreen.kt
- app/src/main/java/be/scri/ui/screens/SelectLanguageScreen.kt
- app/src/main/java/be/scri/ui/screens/settings/SettingsUtil.kt
-   [] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)
---
-   #ISSUE_NUMBER
> Alphabetic order for language 

- app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
- app/src/main/res/layout-land/keyboard_view_keyboard.xml
- app/src/main/res/layout/input_method_view.xml
---
-  closes #486 
-  closes #494
> feat: impl command bar cursor functionality
