.github/ISSUE_TEMPLATE/new_keyboard.yml

What's in here:
- Adds a text form for information on keyboard variants in the `new_keyboard.yml` issue template

docs: add variant info in new_keyboard issue

---

app/src/main/kotlin/org/scribe/views/MyKeyboardView.kt

The pull request is to make the keyboard similar to the iOS Scribe-App by adding white key and a small shadow below the keys

feat:Added Shadow to the keys and reduced border radius 

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/org/scribe/services/EnglishKeyboardIME.kt
app/src/main/kotlin/org/scribe/services/FrenchKeyboardIME.kt
app/src/main/kotlin/org/scribe/services/GermanKeyboardIME.kt
app/src/main/kotlin/org/scribe/services/ItalianKeyboardIME.kt
app/src/main/kotlin/org/scribe/services/PortugueseKeyboardIME.kt
app/src/main/kotlin/org/scribe/services/RussianKeyboardIME.kt
app/src/main/kotlin/org/scribe/services/SimpleKeyboardIME.kt
app/src/main/kotlin/org/scribe/services/SpanishKeyboardIME.kt
app/src/main/kotlin/org/scribe/services/SwedishKeyboardIME.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/method_english.xml
app/src/main/res/xml/method_french.xml
app/src/main/res/xml/method_german.xml
app/src/main/res/xml/method_italian.xml
app/src/main/res/xml/method_portuguese.xml
app/src/main/res/xml/method_russian.xml
app/src/main/res/xml/method_spanish.xml
app/src/main/res/xml/method_swedish.xml

---
This pull request aims to make separate keyboard selection for separate languages into individual keyboards. Through this pull request the user could enable the keyboard that the user wants from the android settings and then when the user selected the keyboard from the input method picker. 
- #15

feat:Added separate keyboard selection for all languages

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/kotlin/be/scri/activities/AboutActivity.kt
app/src/main/kotlin/be/scri/helpers/CustomAdapter.kt
app/src/main/kotlin/be/scri/models/ItemsViewModel.kt
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/activity_wikimedia_scribe.xml
app/src/main/res/layout/card_view_design.xml
app/src/main/res/menu/menu_navigation_bottom.xml
app/src/main/res/values-de/string.xml
app/src/main/res/values-es/string.xml
app/src/main/res/values-sv/string.xml
app/src/main/res/values/string.xml
app/src/main/res/xml/locales_config.xml
app/src/main/res/xml/method_english.xml
app/src/main/res/xml/method_french.xml
app/src/main/res/xml/method_german.xml
app/src/main/res/xml/method_italian.xml
app/src/main/res/xml/method_portuguese.xml
app/src/main/res/xml/method_russian.xml
app/src/main/res/xml/method_spanish.xml
app/src/main/res/xml/method_swedish.xml

---
The strings will now be referenced from the i18n folder, which is a subtree of Scribe-i18n. The About page is fully localized, as it was recently created and all the strings were available. The bottom navigation bar is also localized. However, the other pages could not be localized because the strings were not present. As a result, the old strings.xml is still present. I will create a document for the strings currently referenced in the various files from strings.xml.
-   #44

Reference strings from i18n folder 

---

app/build.gradle
app/src/main/java/be/scri/activities/AboutActivity.kt
app/src/main/java/be/scri/activities/MainActivity.kt
app/src/main/java/be/scri/activities/SettingsActivity.kt
app/src/main/java/be/scri/dialogs/AppSideloadedDialog.kt
app/src/main/java/be/scri/dialogs/ConfirmationAdvancedDialog.kt
app/src/main/java/be/scri/dialogs/ConfirmationDialog.kt
app/src/main/java/be/scri/dialogs/CustomIntervalPickerDialog.kt
app/src/main/java/be/scri/dialogs/RadioGroupDialog.kt
app/src/main/java/be/scri/dialogs/WritePermissionDialog.kt
app/src/main/java/be/scri/extensions/Activity.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/views/MyKeyboardView.kt
app/src/main/java/be/scri/views/bottomactionmenu/BottomActionMenuItemPopup.kt
app/src/main/res/layout/activity_settings.xml
gradle.properties

---
The pull request migrates the application from Kotlin synthetics to Jetpack binding as Kotlin-android-extensions is deprecated.  
-   #68

Migrate From Kotlin Synthetics to Jetpack Binding

---

app/src/main/java/be/scri/views/MyKeyboardView.kt
app/src/main/res/layout-land/keyboard_view_keyboard.xml
app/src/main/res/layout/keyboard_view_command_options.xml
app/src/main/res/layout/keyboard_view_keyboard.xml

---
This PR removed settings cog and extended out the command bar. And I deleted some lines about the cog button in the kotlin scripts.
-   #55

Remove settings cog

---

app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt

---
This PR add an menu item to trigger emoji autosuggestions and a Toast message while switching.
-   #64

Add Autosuggest emojis menu item

---

app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt
app/src/main/java/be/scri/helpers/CustomAdapter.kt
app/src/main/java/be/scri/models/SwitchItem.kt
app/src/main/res/layout/card_view_with_switch.xml

---
I've added a new `description` attribute to `switchItem`, and included descriptions for the current language setting items.
-   #83

Add Descriptions to Language Settings

---

app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/res/xml/keys_letters_german.xml
build.gradle.kts
gradle.properties

---
- This pull request addresses a critical issue where the keyboard would crash either when the delete key was used or when switching to the numbers view. The  problem was that translate method and the various ScribeStates changing the toolbar. Specifically, the abstract class code responsible for managing these interactions was  causing a NullPointerException. For fixing it I have made the function for changing in the individual language keyboards and the individual implementation of the functions for changing in the abstract class. 
- I have also upgraded the Gradle to 8.6.0 
-   #123

fix:Fixed Null Point Error due to toolbar being changed in Language IME

---

app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/java/be/scri/views/MyKeyboardView.kt
app/src/main/res/layout/keyboard_view_command_options.xml
app/src/main/res/values-night-v31/colors.xml
app/src/main/res/values/colors.xml

---
- The pull request corrects the color of the toolbar and command icons and accordingly changes the color of the enter key when in other modes except idle mode. 
-   #121

fix:Corrected the keyboard color and keys colors based on condtions

---

app/build.gradle.kts
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
build.gradle.kts

---
The pull request implements switching the text proxy to the command bar when it is shown. In specific there is a switch for all states except the select command state and idle state.
-   #137

Implement switch text proxy to the command bar when shown 

---

app/src/main/java/be/scri/fragments/AboutFragment.kt
app/src/main/java/be/scri/fragments/MainFragment.kt
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/views/MyKeyboardView.kt
app/src/main/res/drawable/rounded_button.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/keyboard_view_keyboard.xml

The PR implements the Install Keyboards for the settings page during the first install for the user. On Selection of the keyboard language select language settings for the individual settings shows up. 
-   #119

feat:Implemented Install Keyboard Page

---

app/src/main/res/layout/fragment_main.xml
app/src/main/res/layout/fragment_privacy_policy.xml
app/src/main/res/layout/fragment_third_party.xml
app/src/main/res/layout/fragment_wikimedia_scribe.xml
app/src/main/res/values-night-v31/colors.xml
app/src/main/res/values-v31/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

---
This PR fixes dark mode coloring for the main screen button as well as corner polygons on a few screens according to the [figma design](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=581-1539&t=wP5sMYaHXkKslhGE-4).
Apologies apparently the color coming across is not what I see in the app running on my phone.. It's the same as figma I assure you.
-   #164

Growabeard fix darkmode coloration

---

app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt
app/src/main/java/be/scri/fragments/SettingsFragment.kt
app/src/main/java/be/scri/helpers/CustomAdapter.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/res/layout/fragment_third_party.xml
app/src/main/res/xml/keys_letter_german_without_accent_character.xml
app/src/main/res/xml/keys_letter_spanish_without_accent_character.xml
app/src/main/res/xml/keys_letter_swedish_without_accent_characters.xml
app/src/main/res/xml/keys_letters_german.xml

---
- The pull request allows disabling and enabling accent characters in the German, Swedish, and Spanish keyboards. By default they are enabled. 
-   #67 
-   #65

Implement disable and enable of  accent characters

---

app/src/main/res/layout/custom_action_bar_layout.xml

---
This PR fixes the custom action bar so the title doesn't get cut off when changing themes.
Test steps:
1. Set device theme to dark theme.
2. Open app.
3. Navigate to Settings screen.
4. Change device theme to light theme.
5. Open app again.
6. Verify that the title is full "Settings"
7. Repeat steps 1-6 with opposite themes, for good measure.
-   #151

Fixing title to fill full width so names don't get cut off.

---

app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/res/layout/keyboard_view_command_options.xml

---
This PR adds dividers between the autosuggestion buttons.
Since the separator already exists, I made minor adjustments to the [keyboard_view_command_options.xml](https://github.com/scribe-org/Scribe-Android/blob/main/app/src/main/res/layout/keyboard_view_command_options.xml) file.
Please let me know if this approach is incorrect or if there are other considerations I should keep in mind. I look forward to your feedback! :)
Thank you!
-   #122

add dividers between autosuggestion #122

---

app/build.gradle.kts
app/src/main/java/be/scri/fragments/AboutFragment.kt

This commit will add an action for "rate scribe"
---
-   #165

Add action for "rate scribe"

---

app/build.gradle.kts
app/src/test/kotlin/helpers/AlphanumericComparatorTest.kt

Add Junit 5 and Mockk test dependencies with simple test
---
This change adds dependencies to enable writing unit tests including JUnit 5, a dependency to support use of JUnit 5 for android tests, and MockK following details and discussion from #181 
I added a simple test for a utility class as an example.
I ran the following commands to test:
* `./gradlew test`
* `./gradlew check`
For each of these, I verified they fail when expected (set assertions to be incorrect) and pass otherwise.
Once this change is merged, there are a few follow ups needed - I can create issues for these so they can be done later:
* Test code conventions (naming, organization, …

Feat: Add unit testing dependencies

---

app/src/main/java/be/scri/views/MyKeyboardView.kt
detekt.yml

---
This PR fixes linting issues due to Large Class Block by removing the line of code:
```
EmptyCatchBlock:
active: true
```
-   #125

Update detekt.yml to fix the large class lint issue

---

app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt
app/src/main/java/be/scri/helpers/MyKeyboard.kt
app/src/main/java/be/scri/views/MyKeyboardView.kt
detekt.yml

This commit will add suppressions for "Long method"
---
-   #111

Add suppressions

---

app/src/main/java/be/scri/fragments/MainFragment.kt
app/src/main/res/layout/fragment_main.xml

---
this is what it looks like after change the icon size and aligned it with text 
-   #153

Fixes to installation icon size and menu control

---

app/src/main/java/be/scri/activities/MainActivity.kt

* Ensure the app exits on back press from the first page.
---
This pull request fixes the issue where the app did not exit when the back button was pressed on the first page. The updated logic now ensures that the app calls finish() to exit when the back button is pressed on the first page, enhancing the user experience.
-   #206

Fix back button not exiting app

---

.github/workflows/pr_unit_test.yaml

---
Add PR workflow to run unit tests via the gradle test task.
Tested by running `./gradlew test` locally and making sure tests pass and fail as expected.
PR workflow will run on this PR.
-   #195

feat: Add unit test check to PR workflows

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
app/src/main/java/be/scri/extensions/ContextStyling.kt
app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt
app/src/main/java/be/scri/fragments/PrivacyPolicyFragment.kt
app/src/main/java/be/scri/helpers/MyKeyboard.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/views/CustomDividerItemDecoration.kt
app/src/main/java/be/scri/views/MyKeyboardView.kt
detekt.yml

---
This PR addresses the issue of lines of code exceeding the maximum allowed line length, as specified in our coding standards. Long lines can be hard to read and maintain, so I've refactored the relevant code to improve readability and adhere to the established guidelines.
**Changes Made:**
- Refactored methods and lines of code that exceeded the maximum line length.
- Used string concatenation and multi-line formatting for better clarity and maintainability.
**Example Before:**
```kotlin
fun someLongMethodName(param1: String, param2: Int, param3: Boolean): String {
val longString = "This is an example of a very long string that exceeds the maximum …
```

Refactor Long Lines of Code for Improved Readability

---

app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt

---
This PR is fixing the detekt issue TooManyFunctions for the various language KeyboardIME classes.
Disclaimer: yes I know this is pulling up functions to the parent class which already violates the detekt issues. However, I think there is something to be gained in clearing up duplicate code.
To test: turn off the detekt TooManyFunctions issue and run `./gradlew detekt` and observe the output on main branch.
-   #107

Combining and pulling members up to the superclass.

---

.github/workflows/pr_ktlint_detekt.yaml
.github/workflows/pr_unit_test.yaml
gradle.properties

---
This PR adds support for caching Gradle dependencies in CI workflows to improve build performance.
-   #212

ci: support gradle dependency caching in workflows

---

CONTRIBUTING.md
pre-commit-config.yaml

---
This PR adds pre-commit hooks and related documentation regarding the setup and usage of pre-commit hooks to ensure a cleaner, more consistent codebase for Scribe-Android. The pre-commit hooks will help contributors automatically check for code quality issues, such as trailing whitespaces, missing newlines, and linting errors, before committing their changes.
**Changes Introduced:**
- Added Pre-Commit hooks.
- Added a new section …

Add Pre-commit Hooks and Documentation to Development Environment

---

.pre-commit-config.yaml

---
The PR adds auto-formatting during the pre-commit. Also, for some reason, the pre-commit was not working on my device and some of the other devices on which I tested it. I have added an sh to run the script. Currently, the thing fails if it has to auto format, as there must be changes to the codebase. I am happy to have suggestions so that it does not fail whether it makes changes and also on the changes on adding sh to run the …

feat:Added formating fixes in pre-commit

---

app/src/main/java/be/scri/activities/MainActivity.kt
app/src/main/java/be/scri/extensions/RecyclerView.kt
app/src/main/java/be/scri/fragments/AboutFragment.kt
app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt
app/src/main/java/be/scri/fragments/MainFragment.kt
app/src/main/java/be/scri/fragments/PrivacyPolicyFragment.kt
app/src/main/java/be/scri/fragments/ScribeFragment.kt
app/src/main/java/be/scri/fragments/SettingsFragment.kt
app/src/main/java/be/scri/fragments/ThirdPartyFragment.kt
app/src/main/java/be/scri/fragments/WikimediaScribeFragment.kt
app/src/main/java/be/scri/helpers/PreferencesHelper.kt
app/src/main/java/be/scri/helpers/RatingHelper.kt
app/src/main/java/be/scri/helpers/ShareHelper.kt
app/src/main/java/be/scri/models/ItemsViewModel.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/views/MyKeyboardView.kt
detekt.yml

---
I have gone through the fragments package and the MainActivity to fix the TooManyFunctions detekt issue by refactoring common code and moving out code that was doing work outside the responsibility of the class it was previously in (example: MainActivity getting the preferences for dark mode, when that should be owned by the PreferencesHelper.)
I have added an annotation to the remaining classes (`SimpleKeyboardIME` and …

Fix TooManyFunctions in Fragments and MainActivity.

---

app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/res/drawable/emoji_phone_background_rounded.xml
app/src/main/res/drawable/emoji_tablet_background_rounded.xml

---
I modified the `handleDelete` function for deleting the emoji and set the emoji button to semi-transparent.
-   #226

Fix the Button Deletion Issue

---

app/src/main/java/be/scri/activities/MainActivity.kt
app/src/main/java/be/scri/extensions/ContextStyling.kt
app/src/main/java/be/scri/extensions/Int.kt
app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt
app/src/main/java/be/scri/fragments/PrivacyPolicyFragment.kt
app/src/main/java/be/scri/helpers/AlphanumericComparator.kt
app/src/main/java/be/scri/helpers/CommonsConstants.kt
app/src/main/java/be/scri/helpers/Constants.kt
app/src/main/java/be/scri/helpers/MyKeyboard.kt
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/java/be/scri/views/MyKeyboardView.kt
detekt.yml

---
Thanks to the previous contributors for their refactoring work, which removed a lot of unnecessary code. I only need to modify about 50 formatting errors instead of the 500 I mentioned in #90. 😊
-   #90

Fix Magic Number Issues

---

app/src/main/java/be/scri/fragments/LanguageSettingsFragment.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt

---
This PR fixes two bugs: one is the autosuggest switch not working, and the other is the lag when double tap space with `double space periods` switch turned off.
But the fix for the latter one is a bit of a workaround; I’d be happy to revise it if there is a better way.
-   #231

Fix language settings switches

---

app/build.gradle.kts
app/src/main/java/be/scri/helpers/CustomAdapter.kt
app/src/main/java/be/scri/helpers/HintUtils.kt
app/src/main/java/be/scri/helpers/PreferencesHelper.kt
app/src/main/java/be/scri/helpers/RatingHelper.kt
app/src/main/java/be/scri/helpers/ShareHelper.kt
detekt.yml

---
The Pull request fixes linting issues due to object classes being declared as public classes and Linting issues due to Spread operator. 
-   #91

Fix linting issues due to Spread operator and object classes being declared as Public Classes 

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/be/scri/ui/screens/ThirdPartyScreen.kt
app/src/main/res/values/styles.xml
build.gradle.kts
detekt.yml
lint.xml

---
The pull request adds the `nlopez` Compose rules to the `ktlint` and `detekt` tasks to check for linting issues. It also corrects the existing linting issues that were detected. Additionally, `Slack Compose rules` have been added to the lint checks, ensuring that the IDE can detect any linting issues and provide recommendations for better practices.
-   #240

feat:Added nlopez compose rules for ktlint and detekt

---

app/src/main/java/be/scri/helpers/english/ENInterfaceVariables.kt
app/src/main/java/be/scri/helpers/french/FRInterfaceVariables.kt
app/src/main/java/be/scri/helpers/french/FR_AZERTYInterfaceVariables.kt
app/src/main/java/be/scri/helpers/german/DEInterfaceVariables.kt
app/src/main/java/be/scri/helpers/italian/ITInterfaceVariables.kt
app/src/main/java/be/scri/helpers/portugese/PTInterfaceVariables.kt
app/src/main/java/be/scri/helpers/russian/RUInterfaceVariables.kt
app/src/main/java/be/scri/helpers/spanish/ESInterfaceVariables.kt
app/src/main/java/be/scri/helpers/swedish/SVInterfaceVariables.kt

---
In this PR, I’ve added all required interface variable strings to the keyboard constants for each language. Based on the new approach, these strings are now hard-coded into each keyboard file rather than being localized via Weblate.
-   #214

Added interface variables strings constant to be used in the keyboard 

---

app/src/main/java/be/scri/fragments/AboutFragment.kt
app/src/main/java/be/scri/ui/common/components/AboutPageItem.kt
app/src/main/java/be/scri/ui/common/components/AboutPageItemComp.kt
app/src/main/java/be/scri/ui/common/components/ItemCardContainer.kt
app/src/main/java/be/scri/ui/models/ScribeItem.kt
app/src/main/java/be/scri/ui/screens/AboutScreen.kt

---
The pull request moves the about page to Jetpack Compose
|---|---|
| ![Before](https://github.com/user-attachments/assets/66333ea1-8a90-4c0a-924b-e4d9dc201c89) | ![WhatsApp Image 2024-12-06 at 10 55 20_ea973503](https://github.com/user-attachments/assets/4432a98f-aa0c-4030-9b47-cf76ead5533f)
-   #248

Migrated about page from XML to Jetpack Compose

---

app/src/main/java/be/scri/helpers/DatabaseHelper.kt
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/res/drawable/rounded_drawable.xml
app/src/main/res/values-night-v31/colors.xml
app/src/main/res/values-v31/colors.xml

---
This PR implements Gender | Plural auto suggestion for each word we type. This could be seen while typing a word and the first auto suggest button changes to the gender | PL for plural. 
-   #135

Style first autosuggestion button based on the gender of a word typed 

---

app/src/debug/res/values/strings.xml

---
The app - when you run it with debug mode on a phone - didn't have a label. The issue was that the label in the strings.xml under the debug folder had an empty label. I removed it and now the name is shown propperly.
-   #290

fix: app label name - debug mode

---

app/build.gradle.kts
app/src/main/java/be/scri/services/SimpleKeyboardIME.kt
app/src/main/res/drawable/emoji_phone_background_rounded.xml
app/src/main/res/layout/keyboard_view_command_options.xml

---
This pull request addresses two issues:  
1. **Dark Mode Enhancements** (#289)  
- Changed the Scribe key icon and Cancel key icon colors to white for better visibility in dark mode.  
2. **Emoji Key Background Update** (#288)  
- Made the emoji key background transparent to align with UI design standards.  
- Updated the dark mode color theme to apply white to the specified key icons.  
- Adjusted the emoji key background property to make it transparent.  
- Verified changes across various modes and themes.  
- Added Seperator to emoji key 
---
- Resolves #289  
- Resolves #288  
---
---
- Verified functionality by enabling dark mode and testing the key icons.  
- Confirmed transparency for the emoji key background by checking across light and dark modes.  
Thank you for reviewing …

Change Scribe Key Icon and Cancel Key Icon Colors to White in Dark Mode & Make Emoji Key Background Transparent

---

app/src/main/java/be/scri/helpers/HintUtils.kt
app/src/main/java/be/scri/helpers/KeyboardBase.kt
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/java/be/scri/views/KeyboardView.kt
app/src/main/res/layout-land/keyboard_view_keyboard.xml
app/src/main/res/layout/keyboard_popup_keyboard.xml
app/src/main/res/layout/keyboard_view_command_options.xml
app/src/main/res/layout/keyboard_view_keyboard.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml

---
I renamed the code variable names and XML file names according to this rule.
- `SimpleKeyboardIME` -> `GeneralKeyboardIME`
- `MyKeyboardView` -> `KeyboardView`
- `MyKeyboard` -> `KeyboardBase`
After my initial testing, the app can run normally currently.
-   #223

Rename Keyboard IME

---

app/src/main/assets/data-contracts/de.json
app/src/main/assets/data-contracts/en.json
app/src/main/assets/data-contracts/es.json
app/src/main/assets/data-contracts/fr.json
app/src/main/assets/data-contracts/it.json
app/src/main/assets/data-contracts/pt.json
app/src/main/assets/data-contracts/ru.json
app/src/main/assets/data-contracts/sv.json

---
As discussed in #269 and in recent syncs, we need to set up data contracts that will determine how the end applications present the data coming in from Scribe-Data. This PR sends along my first ideas on them based on the call we had yesterday.
A short synopsis of this:
- For Scribe-iOS all data values are hard coded into the application
- The data might change on Wikidata's end, meaning that the labels and other information …

#269 First iteration of Scribe-Data data contracts

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt

Correct capitalization behavior, fix shift key icon, and handle German plural noun capitalization.
Closes #287
---
This pull request addresses issue #287 by resolving several issues with the command bar:
- **Corrected text capitalization behavior:** Ensured correct capitalization of text entered in the command bar, including proper handling of cases like German plural nouns.
- **Fixed shift key icon behavior:** Corrected an issue …

fix(command-mode): fix shift key and capitalization behaviour

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt

---
This commit addresses issue #298 by:
1. **Automatically switching the keyboard to 'keyboardLetters' after a Scribe command (e.g., translate, conjugate, plural) is selected.** This improves the user experience by streamlining the workflow and reducing the need for manual keyboard mode changes.
2. **Switching the keyboard to 'keyboardLetters' when the user switches to the Idle mode.** This ensures consistent keyboard behavior and …

Fix(general-keyboard): Automatically switch to letter keys after command selection

---

app/build.gradle.kts
app/src/main/assets/data-contracts/de.json
app/src/main/assets/data-contracts/en.json
app/src/main/java/be/scri/helpers/DatabaseFileManager.kt
app/src/main/java/be/scri/helpers/DatabaseHelper.kt
app/src/main/java/be/scri/helpers/DatabaseManagers.kt
app/src/main/java/be/scri/helpers/KeyboardDBHelper/ContractDataLoader.kt
app/src/main/java/be/scri/helpers/KeyboardDBHelper/EmojiDataManager.kt
app/src/main/java/be/scri/helpers/KeyboardDBHelper/GenderDataManager.kt
app/src/main/java/be/scri/helpers/KeyboardDBHelper/PluralFormsManager.kt
app/src/main/java/be/scri/models/DataContract.kt
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/res/drawable/gender_suggestion_button_left_background.xml
app/src/main/res/drawable/gender_suggestion_button_right_background.xml
app/src/main/res/layout/keyboard_view_command_options.xml

---
The PR introduces a Data Contract-based implementation for Noun Suggestion, designed to enhance modularity and flexibility in handling language-specific noun forms. This implementation leverages JSON-defined Data Contracts that are processed using a DataContractModel, located in the app's models module. The model enforces the presence of three essential keys within each contract: numbers, genders, and conjugation. Additionally, …

Implement Data Contract-Based Noun Suggestion with Plural and Gender Handling

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/res/layout/keyboard_view_keyboard.xml

---
This commit addresses issue #286 by improving the cursor behavior within the command bar.
Previously, the cursor remained fixed after the command prompt, even as the user typed input. This has been corrected so that the cursor now dynamically moves to the end of the input text as the user types, providing a more intuitive and user-friendly experience.
-   #286

fix(command-bar): move cursor to end of input after typing

---

app/src/main/java/be/scri/helpers/PreferencesHelper.kt

---
Correct the initial state of the dark mode toggle button to match the device's system dark mode preference on first launch.
Tested on device with both dark mode and light mode enabled in system settings and verified that the dark mode toggle button now correctly matches the system preference on app launch.
Also tested that the toggle button updates when the user changes the dark mode setting within the app.
-   #295

Fix initial state (on app install) of dark mode toggle.

---

app/src/main/java/be/scri/helpers/PreferencesHelper.kt
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/java/be/scri/ui/screens/LanguageSettingsScreen.kt
app/src/main/java/be/scri/ui/screens/settings/SettingsScreen.kt
app/src/main/java/be/scri/ui/screens/settings/SettingsViewModel.kt
app/src/main/java/be/scri/views/KeyboardView.kt

---
This PR moves the vibrate on keypress and show pop up on keypress to the respective language keyboard settings. The PR also fixes the disabling for the popup on keypress and it was currently not working.
-   #141

Move the Vibrate on Keypress and Show Popup on keypress to Language settings 

---

app/build.gradle.kts
app/src/main/java/be/scri/App.kt
app/src/main/java/be/scri/helpers/PreferencesHelper.kt
app/src/main/java/be/scri/navigation/Screen.kt
app/src/main/java/be/scri/ui/screens/LanguageSettingsScreen.kt
app/src/main/java/be/scri/ui/screens/SelectLanguageScreen.kt
app/src/main/res/values/strings.xml

---
Added translation source language option to language settings screen
The actual selection does not work (just a clickable ui item)
I ran my code in Android Studio and saw the option in Settings > Select Installed Keyboard > English
I also ran the ./gradlew lintKotlin detekt test to check my code
-   #149

Added translation source language option to language setting screen

---

app/src/main/java/be/scri/ui/common/appcomponents/HintDialog.kt

---
This pull request is to improve styling of app hints tooltips as described in issue #323
I have:
- changed the button color
- add shadow to button and tooltips
- added horizontal padding
- placed the tooltips slightly lower
- increased font size of OK
-   #323

App hints tooltips

---

app/src/main/java/be/scri/ui/common/components/ClickableItemComp.kt
app/src/main/java/be/scri/ui/common/components/SwitchableItemComp.kt
app/src/main/java/be/scri/ui/screens/InstallationScreen.kt
app/src/main/java/be/scri/ui/screens/settings/SettingsScreen.kt

---
This fix improves the styling of quick tutorial and install keyboard buttons. These button have been styled to look more like the design graphic shown in the linked issue.
|--------|--------|
| ![WhatsApp Image 2025-03-18 at 19 00 37 (1)](https://github.com/user-attachments/assets/16dc31ac-db78-4b77-b69f-357011e71d97) | ![WhatsApp Image 2025-03-18 at 19 00 36 …

Improve the styling of quick tutorial and install keyboard buttons

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/res/drawable/button_background_rounded.xml
app/src/main/res/values/colors.xml

---
Fix command key color inconsistency with Scribe key in dark mode. Now command keys color matches with the scribe key in both light and dark mode. Also fixed the X icon to cancel the command and the command bar color in dark mode. Tested by switching the dark/light modes in app. Also tested by switching the device's theme on Samsung A34 5G. 
-   ##161

Fix dark mode coloration of command bar, X symbol and command keys.

---

app/src/main/java/be/scri/views/KeyboardView.kt
app/src/main/res/drawable/ic_caps_lock_off.xml
app/src/main/res/drawable/ic_caps_lock_on.xml

---
This PR addresses theming issues with the keyboard icons and improves the visual feedback for shift key states. The main improvements include:
1. Fixed the caps lock icon to properly respect the system/user theme in both light and dark modes
2. Applied consistent color filtering to all special keys including caps lock
3. Improved the visual consistency between caps lock on/off states by aligning their dimensions
4. Enhanced the …

Fix Caps Lock Icon Theming and Improve Shift Key Behavior

---

app/src/main/res/drawable/close.xml
app/src/main/res/drawable/ic_scribe_icon_vector.xml

---
Standardize the size of the Scribe key icons. The scribe key icon size is reduced and the size of the X icon to cancel the commands is increased.
-   #341

Standardize the size of the Scribe key icons.

---

app/src/main/res/drawable/cmd_key_background_rounded.xml
app/src/main/res/drawable/scribe_key_background_left_rounded.xml

---
Refined the animation so that it no longer spreads outward from the user's click location. Instead, it now features a subtle, uniform change to indicate the click, aligning with the issue's requirements.
-   #318 
https://github.com/user-attachments/assets/9b2ef300-2cda-4c08-a84a-088958eacbc1

fixed scribe key animation

---

app/src/main/java/be/scri/ui/common/components/AboutPageItemComp.kt
app/src/main/java/be/scri/ui/common/components/ClickableItemComp.kt

---
Fixed animations to span the whole option instead of text and icons
-   #324
https://github.com/user-attachments/assets/238de915-5aa9-45cb-bee5-6bb05472a17a

fixed the click animation on the settings and about page 

---

app/src/main/res/layout/keyboard_view_command_options.xml

---
This fix adds spacing between the scribe key and translate key
|--------|--------|
| ![WhatsApp Image 2025-03-24 at 17 44 45](https://github.com/user-attachments/assets/d5fa95b8-6379-40ac-baae-f9a2ebd61db3) | ![WhatsApp Image 2025-03-24 at 17 44 46](https://github.com/user-attachments/assets/70878b96-cc25-4636-86af-036dc11b93c7)|
- #317

Add spacing between the scribe key and translate key

---

app/src/main/java/be/scri/views/KeyboardView.kt

---
This fix increases the vertical space between key rows, aligning their style with Scribe-iOS and other keyboards.
|------- | ------|
| ![WhatsApp Image 2025-03-24 at 10 13 30](https://github.com/user-attachments/assets/1a674690-62b7-4941-aaf4-f5d58ce5a4a7) | ![WhatsApp Image 2025-03-24 at 10 13 29](https://github.com/user-attachments/assets/810c5056-8175-4c04-b9fe-576cab7690b6)
-   #320

Increase the vertical spacing between key rows

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/res/layout/keyboard_view_command_options.xml

---
This pull request addresses several UI layout issues in the keyboard interface:
1. **Fixed emoji separator visibility**: Previously, only one separator was visible for three emoji buttons, causing emoji buttons to overlap with separators. This has been fixed by properly configuring all separators.
2. **Fixed separator_4 visibility**: Resolved an issue where separator_4 was overlapping with the plural button, causing UI …

 Fix Emoji Separator Visibility and Layout Issues

---

.github/workflows/android_ci.yml
app/build.gradle.kts
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/test/kotlin/helpers/ComprehensiveCoverageTest.kt
build.gradle.kts
scripts/coverage_parser.py

---
The PR introduces coverage report for the PR.
-   #337

Add Coverage Report for  PR

---

app/src/main/java/be/scri/helpers/AlphanumericComparator.kt
app/src/main/java/be/scri/helpers/BaseConfig.kt
app/src/main/java/be/scri/helpers/Config.kt
app/src/main/java/be/scri/helpers/CustomAdapter.kt
app/src/main/java/be/scri/helpers/DatabaseFileManager.kt
app/src/main/java/be/scri/helpers/DatabaseHelper.kt
app/src/main/java/be/scri/helpers/DatabaseManagers.kt
app/src/main/java/be/scri/helpers/HintUtils.kt
app/src/main/java/be/scri/helpers/KeyHandler.kt
app/src/main/java/be/scri/helpers/KeyboardBase.kt
app/src/main/java/be/scri/helpers/PreferencesHelper.kt
app/src/main/java/be/scri/helpers/RatingHelper.kt
app/src/main/java/be/scri/helpers/ShareHelper.kt
app/src/main/java/be/scri/helpers/keyboardDBHelper/ContractDataLoader.kt
app/src/main/java/be/scri/helpers/keyboardDBHelper/EmojiDataManager.kt
app/src/main/java/be/scri/helpers/keyboardDBHelper/GenderDataManager.kt
app/src/main/java/be/scri/helpers/keyboardDBHelper/PluralFormsManager.kt
app/src/main/java/be/scri/helpers/keyboardDBHelper/PrepositionDataManager.kt

---
The PR adds doc comments to all the functions and classes in the helpers directory.
-   #310

Document all functions in the helpers directory

---

app/src/main/java/be/scri/helpers/HintUtils.kt
app/src/main/java/be/scri/helpers/KeyHandler.kt
app/src/main/java/be/scri/helpers/PreferencesHelper.kt
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt

---
The PR introduces the feature to switch the keyboard to the keyboard language selected to be translated from for each language keyboard. The keyboard switches to the selected language from the settings when present in translate mode. 
Closes #265

Implement Translate Mode Keyboard Switch 

---

app/src/main/java/be/scri/ui/common/appcomponents/HintDialog.kt

---
This fix added width to tooltips box
|--------|--------|
| ![WhatsApp Image 2025-04-12 at 08 46 38](https://github.com/user-attachments/assets/096b57a0-9352-423e-8b91-18d931d310c3) | ![WhatsApp Image 2025-04-12 at 08 46 38 (1)](https://github.com/user-attachments/assets/c164dbdc-670f-4e72-8b33-cf362a970fa2)| 
-   #361

fix: Add width to tooltips box

---

app/src/main/java/be/scri/helpers/DatabaseHelper.kt
app/src/main/java/be/scri/helpers/DatabaseManagers.kt
app/src/main/java/be/scri/helpers/PreferencesHelper.kt
app/src/main/java/be/scri/helpers/keyboardDBHelper/TranslationDataManager.kt
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/java/be/scri/ui/screens/LanguageSettingsScreen.kt

---
The PR implements the translate feature. When the user is in the translate mode. The users text on click of the enter gets translated to the destination language from the user selected source language. 
Closes #266

Implement Translate feature for the keyboard

---

app/src/main/java/be/scri/App.kt
app/src/main/java/be/scri/extensions/CommonsContext.kt
app/src/main/java/be/scri/extensions/Context.kt
app/src/main/java/be/scri/extensions/ContextStyling.kt
app/src/main/java/be/scri/extensions/Drawable.kt
app/src/main/java/be/scri/extensions/Int.kt
app/src/main/java/be/scri/extensions/RecyclerView.kt
app/src/main/java/be/scri/extensions/View.kt
app/src/main/java/be/scri/navigation/Screen.kt
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
detekt.yml

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch  
---
This PR adds comprehensive KDoc documentation to the ScribeApp and HandleBackPress composable functions in the root of the application. These functions handle application-wide UI setup and navigation, including theme configuration, pager navigation, bottom navigation behavior, and screen transitions for the main routes like Installation, Settings, and About.
All public-facing composables are now properly documented, which …

docs: Add KDoc documentation for ScribeApp and HandleBackPress in app root

---

app/src/main/java/be/scri/views/CustomDividerItemDecoration.kt
app/src/main/java/be/scri/views/KeyboardView.kt

---
This pull request fixes dangling top-level KDoc comments.
-   #368

Fix dangling top-level kdoc comments

---

app/src/main/java/be/scri/models/DataContract.kt
app/src/main/java/be/scri/models/ItemsViewModel.kt
app/src/main/java/be/scri/models/SwitchItem.kt
app/src/main/java/be/scri/models/TextItem.kt
detekt.yml

---
This pull request documents all public classes within the `be.scri.models` package. The documented classes include:
- `DataContract`, `Genders`, `Conjugation`
- `ItemsViewModel` and its nested `Text` class
- `SwitchItem`, `TextItem`, and base sealed class `Item`
These changes were made to improve maintainability and satisfy Detekt’s documentation requirements. All code style and lint checks were passed successfully.
---
- #372

docs(models): add KDoc for all public classes in be.scri.models package

---

app/build.gradle.kts
app/src/androidTest/kotlin/be/scri/ui/screens/settings/SettingsUtilTest.kt

---
This pull request introduces unit tests for the utility functions in the SettingsUtil class.
-   #356

 Add unit tests for settingsUtil functions

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt

---
**Problem:**
When the Scribe key is clicked and the user enters the `SELECT_COMMAND` state, the text color of the "Translate" button incorrectly changes to black, especially noticeable as the user begins typing. This behavior is inconsistent with the expected UI, where the "Translate" button's text color should remain unchanged (i.e., respect the current dark/light theme) regardless of user input in this state. …

Fix Translate button text color in SELECT_COMMAND state

---

app/src/main/java/be/scri/helpers/HintUtils.kt
app/src/main/java/be/scri/helpers/KeyHandler.kt
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/res/layout/keyboard_view_command_options.xml
app/src/main/res/layout/keyboard_view_keyboard.xml
app/src/main/res/values-land/dimens.xml
app/src/main/res/values/dimens.xml

https://github.com/scribe-org/Scribe-Android/issues/273
---
This pull request implement functionality described in related issue
Other changes:
- Fix scribe key's variable width in command mode
- Move log tag to constants, remove "MY-TAG"
- Extract moving to command and idle states into separate functions to avoid code duplication
-   #273

feat: Add invalid state to keyboard commands and show localized Not in Wikidata

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt

---
I added SHIFT_ON_ONE_CHAR to the onStartInputView to capitalize first letter when opening keyboard and added check to capitalize first letter only when input is none. I also added handleDelete to apply SHIFT_ON_ONE_CHAR again when deleted whole input. 
-   Closes #413

Keyboard should load with keys being capitalized

---

.github/workflows/android_ci.yml

---
Resolves #422 
This PR adds a new `instrumentation_test` job to `.github/workflows/android_ci.yml` to run instrumentation tests using `./gradlew connectedAndroidTest`.
**Testing**:
- Ran `./gradlew connectedAndroidTest` locally to confirm tests pass.
- Verified test reports in `app/build/reports/androidTests/connected/`.
**Notes**:
- Assumed tests exist in `app/src/androidTest`. 
-   closes #422

Add instrumentation test job to android_ci.yml

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt

---
If command input was empty, enter key was not handled even if keyboard was in non-command state (such as idle)
-   #427

fix enter key default behaviour

---

.github/workflows/pr_maintainer_checklist.yaml
app/src/main/java/be/scri/helpers/EmojiUtils.kt
app/src/main/java/be/scri/helpers/KeyboardBase.kt
app/src/main/java/be/scri/services/EnglishKeyboardIME.kt
app/src/main/java/be/scri/services/FrenchKeyboardIME.kt
app/src/main/java/be/scri/services/GeneralKeyboardIME.kt
app/src/main/java/be/scri/services/GermanKeyboardIME.kt
app/src/main/java/be/scri/services/ItalianKeyboardIME.kt
app/src/main/java/be/scri/services/PortugueseKeyboardIME.kt
app/src/main/java/be/scri/services/RussianKeyboardIME.kt
app/src/main/java/be/scri/services/SpanishKeyboardIME.kt
app/src/main/java/be/scri/services/SwedishKeyboardIME.kt
app/src/main/java/be/scri/views/KeyboardView.kt

---
When using a browser's search or URL bar, a period is a frequently used character. This change ensures the period key is always available on the alphabetical layout in this context, regardless of the user's "period and comma" setting.
The implementation works as follows:
- `GeneralKeyboardIME` now detects `IME_ACTION_SEARCH` to force the selection of a keyboard layout that includes the period key.
- `KeyboardBase.loadKeyboard` …

feat(keyboard): add period key to search bar

---

.gitignore
app/src/main/java/be/scri/App.kt
app/src/main/java/be/scri/ui/screens/DefaultCurrencySymbolScreen.kt
app/src/main/java/be/scri/ui/screens/LanguageSettingsScreen.kt

---
This pr adds the frontend implimentation for a menu option to change the currency symbol of the keyboard form the given [reference](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=1328-3971&t=8HKzSkldIZfz8Qkw-0)
-   #417

Added default currency symbol option

---

app/src/androidTest/kotlin/be/scri/helpers/DatabaseTest.kt
app/src/androidTest/kotlin/be/scri/helpers/KeyboardTest.kt

---
This pull request adds a unit test for the PluralFormsManager.getPluralRepresentation method. It verifies the input "cat" for the output "cats".
-   #446

test: add unit test for PluralFormsManager.getPluralRepresentation

---

app/src/main/java/be/scri/views/KeyboardView.kt

---
- Added a focused state visual indicator (using `focusedColor`) to highlight the currently hovered/selected popup character while the user is sliding.
- Added a conditional color section `theme_scribe_blue` for dark mode, `light_scribe_color` otherwise
-   #455

Add Visual Indicator for Selected Popup Characters

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/method.xml
app/src/main/res/xml/method_english.xml
app/src/main/res/xml/method_french.xml
app/src/main/res/xml/method_german.xml
app/src/main/res/xml/method_italian.xml
app/src/main/res/xml/method_portuguese.xml
app/src/main/res/xml/method_russian.xml
app/src/main/res/xml/method_spanish.xml
app/src/main/res/xml/method_swedish.xml

---
The PR changes the language names of the Scribe keyboard in the input method manager screen of android. 
-   #472

chore: update language names to native alphabets (#472)

---

app/src/main/java/be/scri/services/GeneralKeyboardIME.kt

---
- We remove the cursor in conjugate mode.
- We also make sure the entered verb is the same colour as the command bar text colour
- We also ensure that we clean up the states of variables properly. 
-   closes #496

fix command bar to have colon in conjugate mode
